---
name: 'Build and Deploy FalconPlayer'

on:
  workflow_dispatch:
    
jobs:
  fpplatest:
    runs-on: ubuntu-latest
    steps:
      - name: find latest release version
        shell: bash
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/FalconChristmas/fpp/releases/latest | sed -n 's/.*tag_name":\s"\(.*\)".*/\1/p' | head -1)
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
      - name: latest release
        shell: bash
        run: |
          echo $LATEST_RELEASE
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: find if latest release exists on Docker Hub
        shell: bash
        run: |
          echo \
          "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt update
          sudo apt install -y docker-ce-cli
          sudo docker inspect mohankumargupta/fpp
    
    
