---
name: 'Build and Deploy FalconPlayer'

on:
  workflow_dispatch:
    
jobs:
  fpplatest:
    runs-on: ubuntu-latest
    steps:
      - name: find latest release version
        shell: bash
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/FalconChristmas/fpp/releases/latest | sed -n 's/.*tag_name":\s"\(.*\)".*/\1/p' | head -1)
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
      - name: latest release
        shell: bash
        run: |
          echo $LATEST_RELEASE
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: find if latest release exists on Docker Hub
        shell: bash
        run: |
          sudo apt install -y jq
          DOCKERHUB_LATEST_VERSION=$(curl -L "https://hub.docker.com/v2/repositories/mohankumargupta/fpp/tags" | jq '.results | .[] | .name' -r | sed 's/latest//' | sort --version-sort | tail -n 1)
          echo $DOCKERHUB_LATEST_VERSION
          
    
    
